[package]
name = "chunk-parser-derive"
version = "0.4.1"
authors = ["StealthOfKing <sok@monocyte.host>"]
edition = "2021"
license = "GPL-3.0"
description = "chunk_parser attribute macro"

[dependencies]
quote = "1.0"
syn = "2.0"

[lib]
proc-macro = true
